/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * Bandi Swagger
 * [openapi.json](/api/swagger)
 * OpenAPI spec version: 0.1.0
 */
import { customClient } from '../mutator';
export type GetApiPost200ItemMeta = {
  createdAt: string;
  location: string;
};

export type GetApiPost200Item = {
  id: string;
  description: string;
  img: string;
  meta: GetApiPost200ItemMeta;
  title: string;
};

export type GetApiPostPostId200Meta = {
  createdAt: string;
  location: string;
};

export type GetApiPostPostId200 = {
  id: string;
  description: string;
  img: string;
  meta: GetApiPostPostId200Meta;
  title: string;
};

export type GetApiNotifications200Item = {
  title: string;
  date: string;
  img: string;
};

export type GetApiHello200 = {
  message: string;
  createdAt: string;
};

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P,
) => any
  ? P
  : never;

/**
 * say hello

 * @summary greeting
 */
export const getApiHello = (options?: SecondParameter<typeof customClient>) => {
  return customClient<GetApiHello200>(
    { url: `/api/hello`, method: 'get' },
    options,
  );
};

/**
 * recent notification list

 * @summary config
 */
export const getApiNotifications = (
  options?: SecondParameter<typeof customClient>,
) => {
  return customClient<GetApiNotifications200Item[]>(
    { url: `/api/notifications`, method: 'get' },
    options,
  );
};

/**
 * post detail

 * @summary post
 */
export const getApiPostPostId = (
  postId: string,
  options?: SecondParameter<typeof customClient>,
) => {
  return customClient<GetApiPostPostId200>(
    { url: `/api/post/${postId}`, method: 'get' },
    options,
  );
};

/**
 * recent post list

 * @summary post
 */
export const getApiPost = (options?: SecondParameter<typeof customClient>) => {
  return customClient<GetApiPost200Item[]>(
    { url: `/api/post`, method: 'get' },
    options,
  );
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetApiHelloResult = NonNullable<
  Awaited<ReturnType<typeof getApiHello>>
>;
export type GetApiNotificationsResult = NonNullable<
  Awaited<ReturnType<typeof getApiNotifications>>
>;
export type GetApiPostPostIdResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostPostId>>
>;
export type GetApiPostResult = NonNullable<
  Awaited<ReturnType<typeof getApiPost>>
>;
